Added client SSE plugin, updated test template
ktorio/ktor-plugin-registry pull request #36
Opened 2024-01-23 14:20 UTC by bjhham

- Added a client entry for SSE
- Updated the server test template

Also, here's a sample PR for illustrating the file structure in the new plugin registry repository.

2024-01-23 16:09 UTC, marychatte approved these changes
Good work!

2024-01-24 13:31 UTC, vnikolova requested changes
Not exactly related to this PR, but I notice the folders within the`plugins/client/io.ktor` folder have the `client-` prefix and I'd expect the ones  in `plugins/server/io.ktor` to have a `server-` prefix but they don't. Is that on purpose?

2024-01-24 13:31 UTC, vnikolova commented on plugins/client/io.ktor/client-sse/3.0.0-beta-1/documentation.md
> +Client "Server-sent Events" (SSE) plugin for consuming events sent using the
Client "Server-sent Events" (SSE) -> Server-Sent Events (SSE) plugin for the Ktor client.

2024-01-24 13:31 UTC, vnikolova commented on plugins/client/io.ktor/client-sse/3.0.0-beta-1/documentation.md
> +[SSE specification](https://html.spec.whatwg.org/multipage/server-sent-events.html).
You could also refer to the docs: https://ktor.io/docs/3.0.0-beta-1/sse-client.html

2024-01-24 13:31 UTC, vnikolova commented on plugins/server/io.ktor/sse/3.0.0-beta-1/documentation.md
> +Server-Sent Events (SSE) support plugin for sending events using the [SSE specification](https://html.spec.whatwg.org/multipage/server-sent-events.html).
Docs reference: https://ktor.io/docs/3.0.0-beta-1/sse-server.html

2024-01-24 14:32 UTC, bjhham commented
I believe the `client-` prefix in the client plugins is because they came later and they need to be unique.  That's what I inferred from my code archeology anyway 😄 

I don't actually know where the client plugins are referenced from tbh 🤷

2024-01-25 10:59 UTC, vnikolova approved these changes

2024-01-25 13:12 UTC, merged