Add Line Webhook Plugin
ktorio/ktor-plugin-registry pull request #60
Opened 2024-04-06 19:31 UTC by cotrin8672

2024-04-10 10:45 UTC, e5l commented
Hey @cotrin8672, thanks for the contribution!

2024-04-10 12:30 UTC, bjhham requested changes
Thanks for the contribution!

Please run `./gradlew buildRegistry` in this project to ensure your plugin builds.

2024-04-10 12:30 UTC, bjhham commented on plugins/server/io.github.cotrin8672/line-webhook/versions.ktor.yaml
> +"[2.0,)":ktor-line-webhook-plugin:==
This `==` notation is only used for plugins that version in sync with Ktor (i.e. plugins inside the Ktor repository).

Please use this here instead:
```
"[2.0,)": ktor-line-webhook-plugin:1.2.+
```

2024-04-10 12:30 UTC, bjhham commented on plugins/server/io.github.cotrin8672/line-webhook/2.0/documentation.md
> +# Line Webhook Signature Validation Plugin
Please remove the top heading here - the project generator always uses the plugin name automatically.

2024-04-10 12:30 UTC, bjhham commented on plugins/server/io.github.cotrin8672/line-webhook/2.0/routing.kt
> +import LineWebhook
I believe this import should be pointing to your package.

2024-04-10 22:14 UTC, cotrin8672 commented
Thank you for your comment, @bjhham. Following your build request, I have run `./gradlew buildRegistry` in my local environment and have confirmed that the build completes successfully. If there are any issues, please don't hesitate to let me know.

2024-04-11 08:26 UTC, bjhham commented on plugins/server/io.github.cotrin8672/line-webhook/2.0/documentation.md
> +```gradle
Please change this to kotlin - using gradle here will break our markdown formatting.

2024-04-12 08:43 UTC, bjhham approved these changes
Looks great, thanks!

2024-04-12 08:44 UTC, merged